name: flutter_bot
description: A discord bot for Flutter Docs search
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0

dependencies: 
  dotenv: ^3.0.0
  nyxx: ^2.0.0-rc.12
  web_scraper: ^0.1.4
